name: firebase_dart
description: A port of the Firebase database, auth and storage client to pure Dart code, usable on different platforms
version: 1.0.0-dev.24
homepage: https://github.com/appsup-dart/firebase_dart

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  quiver: ^3.0.0
  async: ^2.5.0
  logging: ^1.0.0
  sortedmap: ^0.5.0-nullsafety.0
  web_socket_channel: ^2.0.0
  stream_channel: ^2.1.0
  collection: ^1.15.0
  meta: ^1.3.0
  jose: ^0.3.0-nullsafety.2
  clock: ^1.1.0
  googleapis: ^2.0.0
  googleapis_auth: ^1.1.0
  openid_client: ^0.4.0-nullsafety.0
  hive: ^2.0.0
  rxdart: ^0.26.0
  http: ^0.13.0
  pedantic: ^1.11.0
  _discoveryapis_commons: ^1.0.0
  expressions: ^0.2.0
  uuid: ^3.0.1
  crypto: ^3.0.0

dev_dependencies:
  test: ^1.16.5
  fake_async: ^1.2.0
  benchmark_harness: ^2.0.0
