name: firebase_dart
description: A port of the Firebase database client to pure Dart code, usable on different platforms
version: 0.7.15+4
author: Rik Bellens <rik.bellens@appsup.be>
homepage: https://github.com/appsup-dart/firebase_dart

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  quiver: '>=0.22.0 <3.0.0'
  async: '>=1.13.0 <3.0.0'
  crypto: '>=2.0.1 <3.0.0'
  logging: '>=0.11.0 <0.12.0'
  sortedmap: '^0.4.1'
  web_socket_channel: '>=1.0.4 <2.0.0'
  stream_channel: '^2.0.0'
  collection: '^1.9.1'
  meta: '^1.1.5'
  jose: ^0.1.2

dev_dependencies:
  test: '>=0.12.0 <2.0.0'
  pedantic: ^1.9.0
