name: firebase_dart_plus
description: Some additional features for the `firebase_dart` package.
version: 0.1.0-dev.3
homepage: https://github.com/appsup-dart/firebase_dart

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  firebase_dart: ^1.1.0-dev.11
  sortedmap: ^0.5.3
  rxdart: ^0.27.7

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
